
package net.wasnot.android.calculator.realm;

/**
 * Created by akihiroaida on 15/06/02.
 */
//public class CalcurateResult extends RealmObject {
//    private String          name;
//    private int             age;
//
//    @Ignore
//    private int             sessionId;
//
//    // Standard getters & setters generated by your IDE…
//
// }
